---
title: "Group Document"
format: html
editor: visual
---

### Astrid (s203523)

biology is like magic - but real

```{r}
b<-5
b+3
```

### New analysis

So this is a very exciting analysis where I will multiply two numbers

```{r}
number1<-5
number2<-9
analysis<-number1*number2
```

### Emma (s203564)

Hi my name is Emma.

I will add a chunk of code:

```{r}
#| label: "code1"

2 + 2

```

```{r}
#| label: "code2"

x <- c(3, 5, 1, 7, 34, 6, 5, 8, 90)

sum(x)
mean(x)
sd(x)
```

# New analysis

I love math

```{r}
5+6
5-6
5/6
5*6
```

### Yayi (s243559)

calculate the average of student number

```{r}
avg <- (203523 + 203564 + 243559 + 193769 + 203544) / 5

avg
```

New feature

```{r}
stu_num <- c(203523, 203564, 243559, 193769, 203544)
stu_stat <- c(sum(stu_num), mean(stu_num), sd(stu_num))

stu_stat
```

### Andrea (s193769)

HEJ!

```{r}
library("tidyverse")
```

#### New analysis

```{r}
2+3
```

### Asta (s203544)

Hello

```{r}
2+2
```

#### New analysis  

Make an analysis

```{r}
8*2
```
